# @package _global_

model:
  loss_fn: null
  likelihood:
    _target_: darts.utils.likelihood_models.QuantileRegression
    quantiles:
      -   0.01
      -   0.05
      -   0.1
      -   0.15
      -   0.2
      -   0.25
      -   0.3
      -   0.4
      -   0.5
      -   0.6
      -   0.7
      -   0.75
      -   0.8
      -   0.85
      -   0.9
      -   0.95
      -   0.99
